apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: backend.canary-mesh.svc.cluster.local
  namespace: canary-mesh
spec:
  routes:
    - name: GET /api/data
      condition:
        method: GET
        pathRegex: /api/data
      isRetryable: true
      timeout: 500ms
